export const products = [
  {
    id: 1,
    name: "Quantum X Pro Headphones",
    price: 299.99,
    description: "Experience unparalleled audio clarity with active noise cancellation and a 40-hour battery life. Designed for audiophiles.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800",
    category: "Audio",
    rating: 4.8,
    reviews: 124,
    badge: "New",
  },
  {
    id: 2,
    name: "Nebula Smart Watch Series 4",
    price: 199.50,
    description: "Track your health, receive notifications, and look stylish. Features an OLED display and titanium casing.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800",
    category: "Wearables",
    rating: 4.6,
    reviews: 89,
    badge: "Sale",
  },
  {
    id: 3,
    name: "Zenith Mechanical Keyboard",
    price: 149.00,
    description: "Customizable RGB lighting, tactile switches, and an ergonomic design for the ultimate typing experience.",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    rating: 4.9,
    reviews: 210,
  },
  {
    id: 4,
    name: "Luminary Desk Lamp",
    price: 89.99,
    description: "Minimalist LED desk lamp with adjustable color temperature and brightness. Perfect for any workspace.",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800",
    category: "Home",
    rating: 4.5,
    reviews: 56,
  },
  {
    id: 5,
    name: "Aura Noise-Isolating Earbuds",
    price: 129.99,
    description: "Compact wireless earbuds delivering deep bass and crisp highs. Water-resistant and perfect for workouts.",
    image: "https://images.unsplash.com/photo-1572569432755-9ee24b8df6b8?auto=format&fit=crop&q=80&w=800",
    category: "Audio",
    rating: 4.7,
    reviews: 342,
    badge: "Sale",
  },
  {
    id: 6,
    name: "Nova 4K Action Camera",
    price: 349.00,
    description: "Capture your adventures in stunning 4K resolution. Waterproof and rugged for extreme conditions.",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&q=80&w=800",
    category: "Cameras",
    rating: 4.4,
    reviews: 78,
  }
];
